### ISSUE TITLE
hello，很想学习一下该商城小程序，但是本地无法跑起来

### ISSUE THREAD

**Issue by fuxun2008** [coolhwm/leshare-mina#3]
## 请问可以提供一下跑起来的步骤吗？或者APP_ID，希望能学习楼主强大的编码技巧~

**Comment by coolhwm** [comment]
![配置](https://user-images.githubusercontent.com/20462043/27943275-4cbb8336-6310-11e7-9f2c-5589ba02a2cb.png)
你好，把这些都勾上就可以在微信开发者工具中运行

**Comment by fuxun2008** [comment]
![image](https://user-images.githubusercontent.com/4995935/27944446-80268fd2-6319-11e7-9396-aa71c0d14eb2.png)
![image](https://user-images.githubusercontent.com/4995935/27944464-99112b2e-6319-11e7-916d-2d283edc7520.png)
你好，我都勾选上了，方便添加QQ联系吗？大神~

**Comment by fuxun2008** [comment]
补充：微信号 fuxun8082

**Comment by coolhwm** [comment]
你好，抱歉，目前后端暂不支持无APPID登录模式，后续会开放测试节点

**Comment by coolhwm** [comment]
测试方式我QQ邮箱发给你了，可以临时登录

**Comment by jsm1003** [comment]
你好 @coolhwm 也发给我一份吧，谢谢啦
