### ISSUE TITLE
您好，写的非常好，能否私发一个地址给看看呢

### ISSUE THREAD

**Issue by phpcws** [coolhwm/leshare-mina#4]
想学习您的小程序，能否私发一个地址看下1278703730@qq.com 谢谢

**Comment by coolhwm** [comment]
已回复，请按照邮件操作

**Comment by phpcws** [comment]
@coolhwm 已收到，谢谢

**Comment by bdmqy** [comment]
同求学习 847244442@qq.com  谢谢

**Comment by coolhwm** [comment]
已回复，请按邮件操作

**Comment by bdmqy** [comment]
谢谢

**Comment by jsm1003** [comment]
838432498@qq.com，我也想看看，谢谢啦

**Comment by osjj** [comment]
597167998@qq.com，也给我分享一下吧，谢谢了🙏

**Comment by jiuqiang** [comment]
11433140@qq.com 关注很长时间了，学习一下

**Comment by bjwen94111** [comment]
datange@foxmail.com,求地址呢？另外后端的可以开源吗？

**Comment by jsm1003** [comment]
@phpcws @bdmqy 能不能发给我一份啊，up主没给我发

**Comment by FengZeming** [comment]
亲我也想看看学习给我发一份吧 多谢啦~~~

**Comment by FengZeming** [comment]
我看了你的代码写的很好基于wepy的那个我在学习 也希望给我发一个

**Comment by FengZeming** [comment]
23966213@qq.com

**Comment by KhangKH** [comment]
希望楼主给我也发一个学习一下，谢谢，1479981275@qq.com

**Comment by KhangKH** [comment]
并且之前没做过小程序，想问下这个工程如何启起来？

**Comment by KhangKH** [comment]
以及求后端开源代码1479981275@qq.com，谢谢

**Comment by jalessl** [comment]
你好，clone了代码，部分还是不是很懂，能不能也发下地址呀，邮箱：ssl_jale0625@126.com  非常感谢！什么时候看到了，发送都是可以的，谢谢啦！

**Comment by tornadozz** [comment]
同求发一份学习一下，非常感谢！ 116326286@qq.com

**Comment by dbl520** [comment]
2239146847@qq.com可以发一下么

**Comment by shenzhuan** [comment]
这个有后台吗？

**Comment by aben1188** [comment]
同求一份了解一下，谢谢！ lin99@139.com

**Comment by lnys** [comment]
同求一份了解一下，谢谢！niancode@gmail.com

**Comment by andy7076** [comment]
同求一份地址了解一下，谢谢！ wyz@yyfollower.com

**Comment by aliang888** [comment]
下载的包，看不到效果，怎么能在本地运行起来看效果呢？jeman888@qq.com，谢谢

**Comment by ghost** [comment]
请问后端API用的什么呢？

**Comment by juanjuan01** [comment]
1300570732@qq.com 同求

**Comment by coolhwm** [comment]
@jiuqiang  该工程已迁移到 https://github.com/coolhwm/leshare-shop-wepy
